Fix short-circuit or turning into ternaries in 2.3.7+ games
UnderminersTeam/UndertaleModTool pull request #1770
Opened 2024-05-25 20:07 UTC by CST1229

Fixes a regression caused by #1717

## Description
This PR should fix || turning into ternaries like `left ? true : right` in 2.3.7 games. This as just caused by the detection for them only checking for the *numbers* 1/0, but now that they can be casted into booleans they must also check for true/false too.

### Caveats
idk

### Notes

2024-05-28 20:19 UTC, Miepee requested changes

2024-05-28 20:19 UTC, Miepee commented on Underanalyzer
you should remove this submodule.

2024-05-28 20:19 UTC, Miepee commented on UndertaleModLib/Decompiler/Decompiler.cs
> +        private static bool TestBoolLike(Statement statement, bool boolean, DecompileContext context = null)
`context` is never used.

2024-05-28 20:59 UTC, CST1229 commented on Underanalyzer
whoops (i was testing collinator's underanalyzer branch before and i guess git did a git thing)

2024-05-29 07:59 UTC, Miepee approved these changes

2024-05-31 21:02 UTC, Jacky720 approved these changes

2024-05-31 21:02 UTC, merged