Manually add DEBUG constant to nightly builds
UnderminersTeam/UndertaleModTool pull request #1893
Opened 2024-08-27 16:10 UTC by colinator27

## Description
It seems that the updater button has completely vanished from nightly/bleeding edge builds, presumably because `DEBUG` isn't being defined correctly. Not sure if we should apply this to other workflows, too.

### Caveats
Not sure if there's some other configuration thing I'm missing, or if this is how the compiler is meant to work.

2024-08-27 17:45 UTC, Miepee requested changes
This seems wrong, the -c configuration should already handle DEBUG being set.
Maybe it needs to be -c DEBUG instead of -c Debug?

2024-08-27 18:03 UTC, colinator27 commented
> This seems wrong, the -c configuration should already handle DEBUG being set. Maybe it needs to be -c DEBUG instead of -c Debug?

I don't think so, the configuration name *should* be `Debug`. Not sure what's supposed to control `DEBUG` being defined, but it's definitely not in any project files right now. Some docs on https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-directives suggest that it should be defined automatically, but it's clearly not happening right now. Maybe it's just an IDE thing for some reason?

2024-11-25 11:00 UTC, Miepee requested changes

2024-11-25 11:00 UTC, Miepee commented on .github/workflows/publish_gui_nightly.yml
> +        dotnet publish UndertaleModTool -c ${{ matrix.configuration }} -r win-x64 -p:DefineConstants="SHOW_COMMIT_HASH;DEBUG" --self-contained ${{ matrix.bundled }} -p:PublishSingleFile=${{ matrix.si
Can you add a comment above this with `# FIXME: debug constant should automatically be applied, but for some reason it isn't`

2024-12-01 23:53 UTC, Miepee approved these changes

2024-12-01 23:53 UTC, merged