Added way to add creation code in rooms and instances
UnderminersTeam/UndertaleModTool pull request #1901
Opened 2024-09-04 03:10 UTC by luizzeroxis

## Description
Made so the little + icon on creation code in rooms and instances can actually create the script instead of giving an error. Fixes issue #1900. Based on code from #1412.

### Caveats
I tried to make it in a way that it could be expanded with other stuff. Maybe you could create derived classes from UndertaleObjectReference instead, so it doesn't clutter it up with a bunch of properties. Also the part that actually creates the code should probably be in the room model, and the part that creates arguments be separated and merged with the one that does that for object events already.

### Notes
None

2024-11-25 11:41 UTC, Miepee requested changes

2024-11-25 11:41 UTC, Miepee commented on UndertaleModTool/Controls/UndertaleObjectReference.xaml.cs
> +                        }
please condense these

2024-11-25 11:41 UTC, Miepee commented on UndertaleModTool/Controls/UndertaleObjectReference.xaml.cs
> +        UndertaleCode CreationCode(UndertaleData data, string name)
function name feels too generic.

This is adding a code entry, not creation code.
And I'm fairly certain we already have a function in the lib to do exactly that

2024-11-25 21:41 UTC, luizzeroxis commented
Note that this will need to be changed if #1937 is merged

2025-02-09 01:57 UTC, colinator27 commented
Made some changes to ensure duplicate code entries aren't accidentally created, and also added a null check for code locals while I was at it. Will be merging this as long as the builds all work, but I just tested this locally and everything was fine.

2025-02-09 02:02 UTC, merged